src/Entity/Letter.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Sylius\Component\Resource\Model\ResourceInterface;

class Letter implements ResourceInterface
{
    /** @var ?int */
    private $id;

    /** @var ?string */
    private $letter;

    /** @var ?string */
    private $sound;

    /** @var bool */
    private $favorite = true;

    /** @var ?int */
    private $position;

    /** @var Collection|Tag[]|null */
    private $tags;

    /** @var ?LetterLine */
    private $letterLine;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getLetter(): ?string
    {
        return $this->letter;
    }

    /**
     * @param string|null $letter
     */
    public function setLetter(?string $letter): void
    {
        $this->letter = $letter;
    }

    /**
     * @return string|null
     */
    public function getSound(): ?string
    {
        return $this->sound;
    }

    /**
     * @param string|null $sound
     */
    public function setSound(?string $sound): void
    {
        $this->sound = $sound;
    }

    /**
     * @return bool
     */
    public function isFavorite(): bool
    {
        return $this->favorite;
    }

    /**
     * @param bool $favorite
     */
    public function setFavorite(bool $favorite): void
    {
        $this->favorite = $favorite;
    }

    /**
     * @return int|null
     */
    public function getPosition(): ?int
    {
        return $this->position;
    }

    /**
     * @param int|null $position
     */
    public function setPosition(?int $position): void
    {
        $this->position = $position;
    }

    /**
     * @return Tag[]|Collection|null
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * @param Tag $tag
     */
    public function addTag(Tag $tag)
    {
        $this->tags->add($tag);
        $tag->addLetter($this);
    }

    /**
     * @param Tag $tag
     */
    public function removeTag(Tag $tag)
    {
        $this->tags->removeElement($tag);
        $tag->removeLetter($this);
    }

    /**
     * @return array
     */
    public function getTagIds()
    {
        $result = [];
        foreach($this->tags as $tag) {
            $result [$tag->getId()]= $tag->getId();
        }
        return $result;
    }

    public function getTagNames()
    {
        $result = [];
        foreach($this->getTags() as $tag) {
            $result []= $tag->getName();
        }
        return implode(', ', $result);
    }

    public function getGroupColor()
    {
        foreach($this->getTags() as $tag) {
            if ($tag->getHasGroupColor()) {
                return $tag->getGroupColor();
            }
        }
        return null;
    }

    /**
     * @return LetterLine|null
     */
    public function getLetterLine(): ?LetterLine
    {
        return $this->letterLine;
    }

    /**
     * @param LetterLine|null $letterLine
     */
    public function setLetterLine(?LetterLine $letterLine): void
    {
        $this->letterLine = $letterLine;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\Tag;
use App\Repository\LetterLineRepository;
use App\Repository\LetterRepository;
use App\Repository\TagRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class DefaultController extends AbstractController
{
    /** @var TagRepository */
    private $tagRepository;

    /** @var LetterRepository */
    private $letterRepository;

    /** @var LetterLineRepository */
    private $letterLineRepository;

    /** @var EntityManagerInterface */
    private $entityManager;

    /**
     * @param TagRepository $tagRepository
     * @param LetterRepository $letterRepository
     * @param EntityManagerInterface $entityManager
     */
    public function __construct(TagRepository $tagRepository, LetterRepository $letterRepository, LetterLineRepository $letterLineRepository, EntityManagerInterface $entityManager)
    {
        $this->tagRepository = $tagRepository;
        $this->letterRepository = $letterRepository;
        $this->letterLineRepository = $letterLineRepository;
        $this->entityManager = $entityManager;
    }

    public function indexAction()
    {
        $favoriteTags = $this->tagRepository->findBy(['favorite' => true], ['position' => 'asc']);
        $tags = $this->tagRepository->findBy(['favorite' => false], ['position' => 'asc']);

//        $favoriteLetters = $this->letterRepository->findBy(['favorite' => true], ['position' => 'asc']);
        $lines = $this->letterLineRepository->findBy([], ['position' => 'asc']);
//        $letters = $this->letterRepository->findBy(['favorite' => false, 'letterLine' => null], ['position' => 'asc']);

        return $this->render('theme/default/index.html.twig', [
            'favoriteTags' => $favoriteTags,
            'tags' => $tags,
//            'favoriteLetters' => $favoriteLetters,
//            'letters' => $letters,
            'lines' => $lines,
        ]);
    }

    public function favoriteTag(Request $request)
    {
        $id = $request->get('id');
        /** @var Tag $tag */
        $tag = $this->tagRepository->find($id);
        if (!$tag) {
            throw new NotFoundHttpException();
        }

        $tag->setFavorite(true);
        $this->entityManager->flush();

        return new JsonResponse([
            'success' => true
        ]);
    }

    public function unfavoriteTag(Request $request)
    {
        $id = $request->get('id');
        /** @var Tag $tag */
        $tag = $this->tagRepository->find($id);
        if (!$tag) {
            throw new NotFoundHttpException();
        }

        $tag->setFavorite(false);
        $this->entityManager->flush();

        return new JsonResponse([
            'success' => true
        ]);
    }

    public function favoriteLetter(Request $request)
    {
        $id = $request->get('id');
        /** @var Letter $letter */
        $letter = $this->letterRepository->find($id);
        if (!$letter) {
            throw new NotFoundHttpException();
        }

        $letter->setFavorite(true);
        $this->entityManager->flush();

        return new JsonResponse([
            'success' => true
        ]);
    }

    public function unfavoriteLetter(Request $request)
    {
        $id = $request->get('id');
        /** @var Letter $letter */
        $letter = $this->letterRepository->find($id);
        if (!$letter) {
            throw new NotFoundHttpException();
        }

        $letter->setFavorite(false);
        $this->entityManager->flush();

        return new JsonResponse([
            'success' => true
        ]);
    }
}

templates/theme/default/_letters.html.twig
{% for letter in letters %}
    {% set groupColor = letter.groupColor %}
    <li class="letter" data-letter="{{ letter.id }}" data-tags="{{ letter.tagIds|json_encode }}" draggable="true"{% if groupColor %} style="background-color: {{ groupColor }};"{% endif %}>
        <span class="symbol" data-letter-symbol>{{ letter.letter }}</span>
        <span class="sound">{{ letter.sound }}</span>
    </li>
{% endfor %}

templates/theme/default/_lines.html.twig
{% for line in lines %}
    <ul class="letters normal-letters line" data-letters>
        {% for letter in line.letters %}
            {% set groupColor = letter.groupColor %}
            <li class="letter" data-letter="{{ letter.id }}" data-tags="{{ letter.tagIds|json_encode }}" {# draggable="true" #}{% if groupColor %} style="background-color: {{ groupColor }};"{% endif %}>
                <span class="symbol" data-letter-symbol>{{ letter.letter }}</span>
                <span class="sound">{{ letter.sound }}</span>
            </li>
        {% endfor %}
    </ul>
{% endfor %}

templates/theme/default/_tags.html.twig
{% for tag in tags %}
    <li class="tag" data-tag="{{ tag.id }}" data-or-group="{{ tag.orGroup }}" draggable="true"{% if tag.hasGroupColor %} style="background-color: {{ tag.groupColor }};"{% endif %}>
        {% if tag.icon %}<img class="tag-icon" src="{{ media_url(tag.icon, 'tag_icon') }}" alt="tag.name" />{% endif %}
        <span class="tag-name">{{ tag.name }}</span>
    </li>
{% endfor %}

templates/theme/default/index.html.twig
{% extends 'theme/base.html.twig' %}

{% block header %}
    <header>
        <a href="{{ path('app_default_index') }}" class="undecorated-link"><h1>Japanese Texter</h1></a>
        <a href="{{ path('app_frontend_training_index') }}" class="undecorated-link training-link"><h2>Training</h2></a>
    </header>
{% endblock %}

{% block body_class %}class="no-scroll"{% endblock %}

{% block main %}
    <div class="tag-filter-area" data-filter-area>
        <ul class="tags favorite-tags" data-favorite-tags>
            {% include 'theme/default/_tags.html.twig' with { 'tags': favoriteTags } %}
        </ul>
        <ul class="tags normal-tags" data-tags>
            {% include 'theme/default/_tags.html.twig' with { 'tags': tags } %}
        </ul>
    </div>
    <div class="letter-area-container">
        <div class="letter-area" data-letter-area>
            {% include 'theme/default/_lines.html.twig' with { 'lines': lines } %}
        </div>
    </div>
    <div class="output-area" data-output-area>
        <textarea class="output-text-area" data-output-field></textarea>
    </div>
{% endblock %}